enableColors: true

enableGlobalCache: true

enableTelemetry: false

enableTimers: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.8.7.cjs
