name: Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"
jobs:
  prettier:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Get yarn v3 cache directory
        id: get-yarn-v3-cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Restore yarn cache directory
        id: restore-yarn-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-yarn-v3-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn v3 install
        run: yarn install --immutable
        shell: bash
      - name: Publish
        run: |
          yarn config set npmAuthToken ${{ secrets.NPMJS_PUBLISH_TOKEN }} --home
          yarn npm publish --access public
      # $GITHUB_STEP_SUMMARY - success
      - name: Summary (packages/hybrid)
        if: success() && inputs.workspaces != 'true' && inputs.workspace == ''
        run: echo "### Published $(jq '.name' package.json) version $(jq .version package.json) to NPM" >> "$GITHUB_STEP_SUMMARY"
